app:
    resource: "@AppBundle/Controller/"
    type:     annotation

image:
  resource: "@ImageBundle/Resources/config/routing.yml"

image_crud:
  resource: "@ImageBundle/Controller/"
  type: annotation