app:
    resource: "@AppBundle/Controller/"
    type:     annotation

image:
  resource: "@ImageBundle/Resources/config/routing.yml"

image_crud:
  resource: "@ImageBundle/Controller/"
  type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

no_permission:
    path: /sorry
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    "sorry.html.twig"
